### ISSUE TITLE
タイマー機能の設置

### ISSUE THREAD

**Issue by hulk-higakijin** [forPlapoApps/client#12]

**Comment by hulk-higakijin** [comment]
ホークさん

**Comment by hawk0616** [comment]
@hulk-higakijin 
優先順位的には数値表示ロジックが先と思っている

@Daichi-appy 
react-cookiesやりますか？

**Comment by hulk-higakijin** [comment]
@endodaigakuseitaishi 
> 優先順位的には数値表示ロジックが先と思っている

そうですね！できればお願いしたいです
